language: python
python:
#  - "2.7"
#  - "3.2"
#  - "3.3"
  - "3.4"
  - "3.5"
#  - "nightly"
env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install flake8
  - pip install coveralls
  - pip install -q -r requirements.txt

before_script:
  - flake8 django_crypto_fields

script: 
  - coverage run --source=django_crypto_fields manage.py test django_crypto_fields.tests

after_success:
  - coveralls
